import React from "react";
import Image from "next/image";
import styled from "styled-components";
import myWork from "../constants/work";
import Head from "next/head";

const Work = () => {
  return (
    <>
      <Head>
        <title>Jose Raimondi/Work</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Wrapper>
        <div className='page-container'>
          <h1>Some Of My Work</h1>
          <div className='underline'></div>
          <div className='projects-container'>
            {myWork.map((work, index) => {
              return (
                <SingleArticle key={work.id} index={index}>
                  <a
                    className='single-project'
                    href={work.url}
                    target='_blank'
                    rel='noreferrer'
                  >
                    <div className='img-container'>
                      <Image
                        src={work.img}
                        objectFit='cover'
                        layout='fill'
                        alt='work-img'
                      />
                    </div>
                    <p className='desc'>
                      {work.desc}
                      <br />
                      <a href={work.code} target='_blank' rel='noreferrer'>
                        <span> Project&apos;s Code</span>
                      </a>
                    </p>
                  </a>
                </SingleArticle>
              );
            })}
          </div>
        </div>
      </Wrapper>
    </>
  );
};

const SingleArticle = styled.div`
  .single-project {
    min-width: 20rem;
    width: 80vw;
    max-width: 40rem;
    margin: 2rem auto;
    position: relative;
    display: block;
    cursor: pointer;
  }
  .img-container {
    width: 80vw;
    max-width: 30rem;
    height: 20rem;
    overflow: hidden;
    position: relative;
    margin: 0 auto;
    transition: var(--transition);
  }

  .desc {
    background: var(--black-400);
    font-size: 1.2rem;
    padding: 1rem;
    width: 80vw;
    margin: 0 auto;
    transform: translateY(-50%);
    border-radius: 1rem;
    color: var(--primary-300);
    a {
      color: var(--black-100);
      transition: var(--transition);
    }
    a:hover {
      color: var(--primary-500);
    }
  }
  @media screen and (min-width: 768px) {
    .desc {
      width: 35rem;
    }
  }
  @media screen and (min-width: 1350px) {
    .desc {
      background: var(--black-400);
      position: absolute;
      top: 50%;
      left: ${(props) => (props.index % 2 !== 0 ? "-45%" : "70%")};
      bottom: 0;
      font-size: 1.2rem;
      padding: 1rem;
      height: ${(props) => (props.index === 1 ? "12rem" : "10rem")};
      transform: translateY(-50%);
      border-radius: 1rem;
      color: var(--primary-300);
    }
    .img-container {
      opacity: 0.5;
    }
    .single-project:hover {
      .img-container {
        opacity: 1;
      }
    }
  }
`;

const Wrapper = styled.section`
  color: white;
  h1 {
    padding-top: 2rem;
    margin-bottom: 2rem;
    text-align: center;
  }

  .page-container {
    height: auto; //if the page is bigger than 100vh always remember
    padding-bottom: 2rem;
  }
`;

export default Work;
